services:
  - type: web
    name: callbridge-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: GOOGLE_SHEET_URL
        value: "https://docs.google.com/spreadsheets/d/11OMgycK6edFMuiV3FClRk_AyqocgNvshDyXd5uV8a6w/edit"