services:
  - type: web
    name: callbridge-backend
    env: python
    plan: free        # you can change to 'starter' or higher if you need background tasks or more uptime
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_SHEET_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_TWIML_APP_SID
        sync: false
      - key: TWILIO_API_KEY_SID
        sync: false
      - key: TWILIO_API_KEY_SECRET
        sync: false
